name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build-release:
    name: Build Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive_ext: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive_ext: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            archive_ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive_ext: zip

    runs-on: ${{ matrix.os }}

    env:
      RUSTFLAGS: "-C strip=symbols"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Prepare version and validate with Cargo.toml
        id: prep_version
        shell: bash
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
            echo "Version from tag: $VERSION"

            if ! grep -q "^version = \"$VERSION\"" Cargo.toml; then
              echo "Error: Git tag version ($VERSION) does not match the version in Cargo.toml." >&2
              exit 1
            fi
          else
            VERSION="dev"
            echo "Version set to 'dev' for non-tag event."
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare archive name
        id: archive_name
        shell: bash
        run: |
          ARCHIVE_NAME="flatbuffers-language-server-${{ env.VERSION }}-${{ matrix.target }}.${{ matrix.archive_ext }}"
          echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV

      - name: Package binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: tar czvf ${{ env.ARCHIVE_NAME }} -C target/${{ matrix.target }}/release flatbuffers-language-server

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        run: powershell -Command "Compress-Archive -Path target\${{ matrix.target }}\release\flatbuffers-language-server.exe -DestinationPath ${{ env.ARCHIVE_NAME }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
          draft: true
          generate_release_notes: true
